#!/bin/bash

# Run script in .hooks/
HOOK_NAME=commit-msg
PROJECT_HOOK=$(git rev-parse --show-toplevel)/.hooks/$HOOK_NAME

if [ -x "$PROJECT_HOOK" ]; then
  . "$PROJECT_HOOK" $files
fi

# Also check the standard .git/hooks directory
# This can be useful when repositories use hook management tools like husky.
PROJECT_HOOK=$(git rev-parse --show-toplevel)/.git/hooks/$HOOK_NAME

if [ -x "$PROJECT_HOOK" ]; then
  "$PROJECT_HOOK" $files
fi
